# Generated by Django 4.1.4 on 2022-12-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='eCErZ4H6EFPSmCoCThVoyAdNghJ2', max_length=50),
            preserve_default=False,
        ),
    ]
