# Generated by Django 4.1.4 on 2022-12-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='X2B6BcDVXNbCHo1svFqlGmBpMWl1', max_length=50),
        ),
    ]
