# Generated by Django 4.1.4 on 2022-12-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_alter_subscription_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('admin_one_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_one', to='rareapi.user')),
                ('admin_two_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_two', to='rareapi.user')),
                ('modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_user', to='rareapi.user')),
            ],
        ),
        migrations.DeleteModel(
            name='DemotionQueue',
        ),
    ]
